### ISSUE TITLE
Typo accountType_pendapatalDLLView

### ISSUE THREAD

**Issue by sugiana** [open-synergy/l10n_id_opnsyn#43]
Pada file l10n_id_account_type/data/data_AccountType.xml ada typo:
- id="accountType_pendapatalDLLView"

dimana mungkin maksudnya:
- id="accountType_pendapatanDLLView"

Demikian.

**Comment by andhit-r** [comment]
@sugiana terima kasih reportnya. Ya memang itu typo, namun karena typo terjadi di attribute id, maka tidak akan dilakukan perbaikan.

Hal ini didasari pertimbangan sudah ada user yg menggunakan data tersebut. Membetulkannya akan menghapus data dan menimbulkan constraint error.
